<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="2" time="0.054"><testcase classname="test_class.TestClass" file="test_class.py" line="1" name="test_one" time="0.0010349750518798828"></testcase><testcase classname="test_class.TestClass" file="test_class.py" line="5" name="test_two" time="0.0030105113983154297"><failure message="AssertionError: assert False
 +  where False = hasattr(&apos;hello&apos;, &apos;check&apos;)">self = &lt;test_class.TestClass object at 0x000001DD0E3544A8&gt;

    def test_two(self):
        x = &quot;hello&quot;
&gt;       assert hasattr(x, &apos;check&apos;)
E       AssertionError: assert False
E        +  where False = hasattr(&apos;hello&apos;, &apos;check&apos;)

test_class.py:8: AssertionError</failure></testcase></testsuite>